const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: '/images/item-1.jpeg',
    desc: `Fluffy pancakes gemaakt met karnemelk, bloem, eieren en een vleugje vanille. Serveer warm met ahornsiroop en verse bessen.`,
  
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: '/images/item-2.jpeg',
    desc: `Dubbele cheeseburger met gegrild rundvlees, cheddar, sla, tomaat, augurk en een romige burger saus op een geroosterd broodje.`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: '/images/item-3.jpeg',
    desc: `Een enorme chocolade milkshake met vanille-ijs, slagroom, chocoladesaus en stukjes Oreo. Afgetopt met een wafel en sprinkles.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: '/images/item-4.jpeg',
    desc: `Boerenontbijt met roerei, krokant spek, geroosterde aardappeltjes en versgebakken brood met boter.`,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: '/images/item-5.jpeg',
    desc:`Sandwich met geroosterd brood, avocado, knapperige bacon en een gebakken ei met zachte dooier. Perfect met een beetje chilisaus.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: '/images/item-6.jpeg',
    desc: `Romige milkshake met vanille-ijs, melk en gemalen Oreo koekjes. Geserveerd met slagroom en extra Oreo kruimels.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: '/images/item-7.jpeg',
    desc:  `Scrambled eggs met extra veel krokant gebakken bacon, geserveerd met toast en een klein bakje salade.`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: '/images/item-8.jpeg',
    desc: `Klassieke hamburger met rundvlees, cheddar, sla, tomaat, ui, augurk en ketchup op een zacht broodje.`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: '/images/item-9.jpeg',
    desc: `Een troostende aardbeien-banaan milkshake met vanille-ijs en een vleugje honing. Perfect voor een gezellige avond.`,
  },
];
export default menu;
